# Generated by Django 4.2.17 on 2024-12-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('emailId', models.AutoField(primary_key=True, serialize=False)),
                ('C_name', models.CharField(max_length=100)),
                ('C_password', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('aadhar_no', models.CharField(max_length=100)),
            ],
        ),
    ]
